BEGIN;

ALTER TABLE teams ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS espn_team_id text;
CREATE UNIQUE INDEX IF NOT EXISTS teams_name_unique ON teams (name);

INSERT INTO teams (name, slug, logo_url, espn_team_id)
VALUES
  ('Abilene Chrstn', 'abilene-chrstn', '/team-logos/abilene-chrstn.png', '2000'),
  ('Adams St', 'adams-st', '/team-logos/adams-st.png', '2001'),
  ('Adrian', 'adrian', '/team-logos/adrian.png', '2003'),
  ('Air Force', 'air-force', '/team-logos/air-force.png', '2005'),
  ('AK-Anchorage', 'ak-anchorage', '/team-logos/ak-anchorage.png', '1'),
  ('Akron', 'akron', '/team-logos/akron.png', '2006'),
  ('AL-Huntsville', 'al-huntsville', '/team-logos/default.png', '2008'),
  ('Alabama', 'alabama', '/team-logos/alabama.png', '333'),
  ('Alabama A&M', 'alabama-aandm', '/team-logos/alabama-aandm.png', '2010'),
  ('Alabama St', 'alabama-st', '/team-logos/alabama-st.png', '2011'),
  ('Albany St', 'albany-st', '/team-logos/albany-st.png', '2013'),
  ('Albertson', 'albertson', '/team-logos/default.png', '2014'),
  ('Albertus', 'albertus', '/team-logos/default.png', '440'),
  ('Alcorn St', 'alcorn-st', '/team-logos/alcorn-st.png', '2016'),
  ('Alice Lloyd', 'alice-lloyd', '/team-logos/default.png', '484'),
  ('Allegheny', 'allegheny', '/team-logos/allegheny.png', '2018'),
  ('Allen', 'allen', '/team-logos/allen.png', '2019'),
  ('American', 'american', '/team-logos/american.png', '44'),
  ('Anderson (IN)', 'anderson-in', '/team-logos/anderson-in.png', '2023'),
  ('Anderson SC', 'anderson-sc', '/team-logos/default.png', '380'),
  ('Angelo State', 'angelo-state', '/team-logos/angelo-state.png', '2025'),
  ('App State', 'app-state', '/team-logos/app-state.png', '2026'),
  ('Aquinas', 'aquinas', '/team-logos/default.png', '486'),
  ('AR-Pine Bluff', 'ar-pine-bluff', '/team-logos/ar-pine-bluff.png', '2029'),
  ('Arcadia', 'arcadia', '/team-logos/default.png', '407'),
  ('Arizona', 'arizona', '/team-logos/arizona.png', '12'),
  ('Arizona St', 'arizona-st', '/team-logos/arizona-st.png', '9'),
  ('Ark Baptist', 'ark-baptist', '/team-logos/default.png', '2027'),
  ('Ark-Monticello', 'ark-monticello', '/team-logos/ark-monticello.png', '2028'),
  ('Arkansas', 'arkansas', '/team-logos/arkansas.png', '8'),
  ('Arkansas St', 'arkansas-st', '/team-logos/arkansas-st.png', '2032'),
  ('Arkansas Tech', 'arkansas-tech', '/team-logos/arkansas-tech.png', '2033'),
  ('Army', 'army', '/team-logos/army.png', '349'),
  ('Asbury', 'asbury', '/team-logos/default.png', '2036'),
  ('AU Montgomery', 'au-montgomery', '/team-logos/default.png', '2040'),
  ('Auburn', 'auburn', '/team-logos/auburn.png', '2'),
  ('Austin', 'austin', '/team-logos/austin.png', '2045'),
  ('Austin Peay', 'austin-peay', '/team-logos/austin-peay.png', '2046'),
  ('Averett', 'averett', '/team-logos/averett.png', '2047'),
  ('Baker', 'baker', '/team-logos/default.png', '488'),
  ('Ball State', 'ball-state', '/team-logos/ball-state.png', '2050'),
  ('Bapt Bible', 'bapt-bible', '/team-logos/default.png', '405'),
  ('Barber Scotia', 'barber-scotia', '/team-logos/default.png', '489'),
  ('Bates', 'bates', '/team-logos/bates.png', '121'),
  ('Baylor', 'baylor', '/team-logos/baylor.png', '239'),
  ('Belhaven', 'belhaven', '/team-logos/belhaven.png', '2056'),
  ('Bellarmine', 'bellarmine', '/team-logos/bellarmine.png', '91'),
  ('Belmont', 'belmont', '/team-logos/belmont.png', '2057'),
  ('Belmont Abbey', 'belmont-abbey', '/team-logos/belmont-abbey.png', '2058'),
  ('Bennett College', 'bennett-college', '/team-logos/default.png', '464'),
  ('Berea', 'berea', '/team-logos/default.png', '2061'),
  ('Bethany (WV)', 'bethany-wv', '/team-logos/bethany-wv.png', '2062'),
  ('Bethel (TN)', 'bethel-tn', '/team-logos/bethel-tn.png', '2064'),
  ('Bethune', 'bethune', '/team-logos/bethune.png', '2065'),
  ('Binghamton', 'binghamton', '/team-logos/binghamton.png', '2066'),
  ('BIOLA', 'biola', '/team-logos/default.png', '2067'),
  ('Birm-Southern', 'birm-southern', '/team-logos/birm-southern.png', '3'),
  ('Black Hills', 'black-hills', '/team-logos/black-hills.png', '2069'),
  ('Blackburn', 'blackburn', '/team-logos/default.png', '2070'),
  ('Bloomsburg', 'bloomsburg', '/team-logos/bloomsburg.png', '2071'),
  ('Blue Mountain', 'blue-mountain', '/team-logos/default.png', '494'),
  ('Bluefield', 'bluefield', '/team-logos/default.png', '495'),
  ('Bluefield St', 'bluefield-st', '/team-logos/default.png', '2073'),
  ('Boise St', 'boise-st', '/team-logos/boise-st.png', '68'),
  ('Boston College', 'boston-college', '/team-logos/boston-college.png', '103'),
  ('Boston U', 'boston-u', '/team-logos/boston-u.png', '104'),
  ('Bowdoin', 'bowdoin', '/team-logos/bowdoin.png', '340'),
  ('Bowie State', 'bowie-state', '/team-logos/bowie-state.png', '2075'),
  ('Bowling Green', 'bowling-green', '/team-logos/bowling-green.png', '189'),
  ('Bradley', 'bradley', '/team-logos/bradley.png', '71'),
  ('Brandon', 'brandon', '/team-logos/default.png', '2076'),
  ('Brewton Parker', 'brewton-parker', '/team-logos/default.png', '2077'),
  ('Bridgewater St', 'bridgewater-st', '/team-logos/bridgewater-st.png', '18'),
  ('Bridgewater VA', 'bridgewater-va', '/team-logos/bridgewater-va.png', '2079'),
  ('Brown', 'brown', '/team-logos/brown.png', '225'),
  ('Bryan (TN)', 'bryan-tn', '/team-logos/default.png', '2081'),
  ('Bucknell', 'bucknell', '/team-logos/bucknell.png', '2083'),
  ('Buena Vista', 'buena-vista', '/team-logos/buena-vista.png', '63'),
  ('Buffalo', 'buffalo', '/team-logos/buffalo.png', '2084'),
  ('Butler', 'butler', '/team-logos/butler.png', '2086'),
  ('BYU', 'byu', '/team-logos/byu.png', '252'),
  ('C Arkansas', 'c-arkansas', '/team-logos/c-arkansas.png', '2110'),
  ('C Connecticut', 'c-connecticut', '/team-logos/c-connecticut.png', '2115'),
  ('C Michigan', 'c-michigan', '/team-logos/c-michigan.png', '2117'),
  ('Cal Maritime', 'cal-maritime', '/team-logos/default.png', '500'),
  ('Cal Poly', 'cal-poly', '/team-logos/cal-poly.png', '13'),
  ('Cal Sate EB', 'cal-sate-eb', '/team-logos/default.png', '2093'),
  ('California', 'california', '/team-logos/california.png', '25'),
  ('California State Uni', 'california-state-uni', '/team-logos/default.png', '499'),
  ('Calumet', 'calumet', '/team-logos/default.png', '502'),
  ('Cameron', 'cameron', '/team-logos/default.png', '2096'),
  ('Campbell', 'campbell', '/team-logos/campbell.png', '2097'),
  ('Campbellsville', 'campbellsville', '/team-logos/default.png', '2098'),
  ('Canisius', 'canisius', '/team-logos/canisius.png', '2099'),
  ('Capital', 'capital', '/team-logos/capital.png', '424'),
  ('Carroll (MT)', 'carroll-mt', '/team-logos/carroll-mt.png', '2104'),
  ('Catawba', 'catawba', '/team-logos/catawba.png', '2107'),
  ('Catholic', 'catholic', '/team-logos/catholic.png', '2108'),
  ('Cedarville', 'cedarville', '/team-logos/cedarville.png', '2109'),
  ('Cent St OH', 'cent-st-oh', '/team-logos/cent-st-oh.png', '2119'),
  ('Centenary (LA)', 'centenary-la', '/team-logos/centenary-la.png', '2113'),
  ('Centenary (NJ)', 'centenary-nj', '/team-logos/default.png', '2114'),
  ('Chadron St', 'chadron-st', '/team-logos/chadron-st.png', '2123'),
  ('Chaminade', 'chaminade', '/team-logos/chaminade.png', '2124'),
  ('Chapman', 'chapman', '/team-logos/chapman.png', '411'),
  ('Charleston', 'charleston', '/team-logos/charleston.png', '232'),
  ('Charleston So', 'charleston-so', '/team-logos/charleston-so.png', '2127'),
  ('Chattanooga', 'chattanooga', '/team-logos/chattanooga.png', '236'),
  ('Chestnut Hill', 'chestnut-hill', '/team-logos/default.png', '469'),
  ('Cheyney (PA)', 'cheyney-pa', '/team-logos/default.png', '2129'),
  ('Chicago St', 'chicago-st', '/team-logos/chicago-st.png', '2130'),
  ('Christian Bros', 'christian-bros', '/team-logos/default.png', '2131'),
  ('Cincinnati', 'cincinnati', '/team-logos/cincinnati.png', '2132'),
  ('City (NY)', 'city-ny', '/team-logos/default.png', '170'),
  ('Claflin', 'claflin', '/team-logos/default.png', '2133'),
  ('Clark (MA)', 'clark-ma', '/team-logos/default.png', '106'),
  ('Clemson', 'clemson', '/team-logos/clemson.png', '228'),
  ('Cleveland St', 'cleveland-st', '/team-logos/cleveland-st.png', '325'),
  ('Cmbrlnd KY', 'cmbrlnd-ky', '/team-logos/default.png', '511'),
  ('Coastal', 'coastal', '/team-logos/coastal.png', '324'),
  ('Coe', 'coe', '/team-logos/coe.png', '2141'),
  ('Coker', 'coker', '/team-logos/default.png', '229'),
  ('Colby', 'colby', '/team-logos/colby.png', '33'),
  ('Colby Sawyer', 'colby-sawyer', '/team-logos/default.png', '35'),
  ('Colgate', 'colgate', '/team-logos/colgate.png', '2142'),
  ('Colo Mines', 'colo-mines', '/team-logos/colo-mines.png', '2146'),
  ('Colorado', 'colorado', '/team-logos/colorado.png', '38'),
  ('Colorado Coll', 'colorado-coll', '/team-logos/colorado-coll.png', '2144'),
  ('Colorado St', 'colorado-st', '/team-logos/colorado-st.png', '36'),
  ('Columbia', 'columbia', '/team-logos/columbia.png', '171'),
  ('Columbia Coll', 'columbia-coll', '/team-logos/default.png', '504'),
  ('Columbus State', 'columbus-state', '/team-logos/default.png', '413'),
  ('Concord', 'concord', '/team-logos/concord.png', '2148'),
  ('Concordia (NE)', 'concordia-ne', '/team-logos/default.png', '507'),
  ('Concordia (NY)', 'concordia-ny', '/team-logos/default.png', '37'),
  ('Concordia CA', 'concordia-ca', '/team-logos/default.png', '506'),
  ('Concordia OR', 'concordia-or', '/team-logos/default.png', '2150'),
  ('Converse ', 'converse', '/team-logos/default.png', '451'),
  ('Coppin St', 'coppin-st', '/team-logos/coppin-st.png', '2154'),
  ('Cornell', 'cornell', '/team-logos/cornell.png', '172'),
  ('Cornerstone', 'cornerstone', '/team-logos/default.png', '508'),
  ('Covenant', 'covenant', '/team-logos/default.png', '2157'),
  ('Creighton', 'creighton', '/team-logos/creighton.png', '156'),
  ('Crown', 'crown', '/team-logos/crown.png', '509'),
  ('CS D Hills', 'cs-d-hills', '/team-logos/default.png', '2092'),
  ('Culver Stock', 'culver-stock', '/team-logos/default.png', '510'),
  ('Cumberland', 'cumberland', '/team-logos/default.png', '2161'),
  ('Curry', 'curry', '/team-logos/curry.png', '40'),
  ('Dakota St', 'dakota-st', '/team-logos/dakota-st.png', '512'),
  ('Dallas', 'dallas', '/team-logos/default.png', '2163'),
  ('Dallas Baptist', 'dallas-baptist', '/team-logos/dallas-baptist.png', '2164'),
  ('Dartmouth', 'dartmouth', '/team-logos/dartmouth.png', '159'),
  ('Davidson', 'davidson', '/team-logos/davidson.png', '2166'),
  ('Davis & Elkins', 'davis-and-elkins', '/team-logos/default.png', '2167'),
  ('Dayton', 'dayton', '/team-logos/dayton.png', '2168'),
  ('Defiance', 'defiance', '/team-logos/defiance.png', '190'),
  ('Delaware', 'delaware', '/team-logos/delaware.png', '48'),
  ('Delaware St', 'delaware-st', '/team-logos/delaware-st.png', '2169'),
  ('Denison', 'denison', '/team-logos/denison.png', '2171'),
  ('Denver', 'denver', '/team-logos/denver.png', '2172'),
  ('DePaul', 'depaul', '/team-logos/depaul.png', '305'),
  ('Detroit Mercy', 'detroit-mercy', '/team-logos/detroit-mercy.png', '2174'),
  ('Dickinson St', 'dickinson-st', '/team-logos/default.png', '316'),
  ('Dicknsn PA', 'dicknsn-pa', '/team-logos/dicknsn-pa.png', '2175'),
  ('Dillard', 'dillard', '/team-logos/default.png', '2176'),
  ('Dist Columbia', 'dist-columbia', '/team-logos/default.png', '2177'),
  ('Dkta Wesleyan', 'dkta-wesleyan', '/team-logos/default.png', '513'),
  ('Doane', 'doane', '/team-logos/default.png', '2178'),
  ('Drake', 'drake', '/team-logos/drake.png', '2181'),
  ('Drexel', 'drexel', '/team-logos/drexel.png', '2182'),
  ('Dubuque', 'dubuque', '/team-logos/dubuque.png', '49'),
  ('Duke', 'duke', '/team-logos/duke.png', '150'),
  ('Duquesne', 'duquesne', '/team-logos/duquesne.png', '2184'),
  ('E Cent OK', 'e-cent-ok', '/team-logos/e-cent-ok.png', '2191'),
  ('E Illinois', 'e-illinois', '/team-logos/e-illinois.png', '2197'),
  ('E Kentucky', 'e-kentucky', '/team-logos/e-kentucky.png', '2198'),
  ('E Menonite', 'e-menonite', '/team-logos/default.png', '2192'),
  ('E Michigan', 'e-michigan', '/team-logos/e-michigan.png', '2199'),
  ('E Nazarene', 'e-nazarene', '/team-logos/default.png', '412'),
  ('E Washington', 'e-washington', '/team-logos/e-washington.png', '331'),
  ('Earlham', 'earlham', '/team-logos/default.png', '2189'),
  ('East Carolina', 'east-carolina', '/team-logos/east-carolina.png', '151'),
  ('Eastern', 'eastern', '/team-logos/eastern.png', '2196'),
  ('Eastern NM', 'eastern-nm', '/team-logos/eastern-nm.png', '2201'),
  ('Eastern Oregon', 'eastern-oregon', '/team-logos/default.png', '2202'),
  ('Eckerd', 'eckerd', '/team-logos/default.png', '2204'),
  ('Edward Waters', 'edward-waters', '/team-logos/edward-waters.png', '2206'),
  ('Elizabeth City', 'elizabeth-city', '/team-logos/elizabeth-city.png', '2207'),
  ('Elmhurst', 'elmhurst', '/team-logos/elmhurst.png', '72'),
  ('Elmira', 'elmira', '/team-logos/elmira.png', '347'),
  ('Elon', 'elon', '/team-logos/elon.png', '2210'),
  ('EMBRYRIDDL', 'embryriddl', '/team-logos/default.png', '520'),
  ('Emmanuel (MA)', 'emmanuel-ma', '/team-logos/default.png', '2211'),
  ('Emory & Henry', 'emory-and-henry', '/team-logos/emory-and-henry.png', '2213'),
  ('Emporia St', 'emporia-st', '/team-logos/emporia-st.png', '2214'),
  ('Erskine', 'erskine', '/team-logos/default.png', '2215'),
  ('ETSU', 'etsu', '/team-logos/etsu.png', '2193'),
  ('Eureka', 'eureka', '/team-logos/eureka.png', '101'),
  ('Evansville', 'evansville', '/team-logos/evansville.png', '339'),
  ('Fairfield', 'fairfield', '/team-logos/fairfield.png', '2217'),
  ('FAU', 'fau', '/team-logos/fau.png', '2226'),
  ('Fayettvlle', 'fayettvlle', '/team-logos/fayettvlle.png', '2220'),
  ('FDU', 'fdu', '/team-logos/fdu.png', '161'),
  ('FDU Florhm', 'fdu-florhm', '/team-logos/fdu-florhm.png', '2221'),
  ('Ferrum', 'ferrum', '/team-logos/ferrum.png', '366'),
  ('FGCU', 'fgcu', '/team-logos/fgcu.png', '526'),
  ('Fisher', 'fisher', '/team-logos/default.png', '524'),
  ('Fisk', 'fisk', '/team-logos/fisk.png', '2225'),
  ('Fitchburg', 'fitchburg', '/team-logos/fitchburg.png', '114'),
  ('FIU', 'fiu', '/team-logos/fiu.png', '2229'),
  ('FL Memorial', 'fl-memorial', '/team-logos/default.png', '2227'),
  ('Flagler', 'flagler', '/team-logos/flagler.png', '2228'),
  ('Florida', 'florida', '/team-logos/florida.png', '57'),
  ('Florida A&M', 'florida-aandm', '/team-logos/florida-aandm.png', '50'),
  ('Florida St', 'florida-st', '/team-logos/florida-st.png', '52'),
  ('Florida Tech', 'florida-tech', '/team-logos/florida-tech.png', '53'),
  ('Fordham', 'fordham', '/team-logos/fordham.png', '2230'),
  ('Fort Lewis', 'fort-lewis', '/team-logos/fort-lewis.png', '2237'),
  ('Fort Valley St', 'fort-valley-st', '/team-logos/fort-valley-st.png', '2232'),
  ('Francs Mar', 'francs-mar', '/team-logos/default.png', '230'),
  ('Frank Pierce', 'frank-pierce', '/team-logos/frank-pierce.png', '144'),
  ('Franklin', 'franklin', '/team-logos/franklin.png', '2233'),
  ('Fresno Pacific', 'fresno-pacific', '/team-logos/fresno-pacific.png', '2235'),
  ('Fresno St', 'fresno-st', '/team-logos/fresno-st.png', '278'),
  ('Fullerton', 'fullerton', '/team-logos/fullerton.png', '2239'),
  ('Furman', 'furman', '/team-logos/furman.png', '231'),
  ('G Washington', 'g-washington', '/team-logos/g-washington.png', '45'),
  ('GA College', 'ga-college', '/team-logos/default.png', '2246'),
  ('GA Southern', 'ga-southern', '/team-logos/ga-southern.png', '290'),
  ('Gallaudet', 'gallaudet', '/team-logos/gallaudet.png', '417'),
  ('Gardner-Webb', 'gardner-webb', '/team-logos/gardner-webb.png', '2241'),
  ('Geneva', 'geneva', '/team-logos/geneva.png', '2242'),
  ('George Fox', 'george-fox', '/team-logos/george-fox.png', '415'),
  ('George Mason', 'george-mason', '/team-logos/george-mason.png', '2244'),
  ('Georgetown', 'georgetown', '/team-logos/georgetown.png', '46'),
  ('Georgia', 'georgia', '/team-logos/georgia.png', '61'),
  ('Georgia St', 'georgia-st', '/team-logos/georgia-st.png', '2247'),
  ('Georgia Tech', 'georgia-tech', '/team-logos/georgia-tech.png', '59'),
  ('Gonzaga', 'gonzaga', '/team-logos/gonzaga.png', '2250'),
  ('Goucher', 'goucher', '/team-logos/default.png', '2251'),
  ('Grace', 'grace', '/team-logos/default.png', '2252'),
  ('Graceland', 'graceland', '/team-logos/graceland.png', '530'),
  ('Grand Canyon', 'grand-canyon', '/team-logos/grand-canyon.png', '2253'),
  ('Greensboro', 'greensboro', '/team-logos/greensboro.png', '2256'),
  ('Greenville', 'greenville', '/team-logos/greenville.png', '2257'),
  ('Grove City', 'grove-city', '/team-logos/grove-city.png', '146'),
  ('Grt Falls', 'grt-falls', '/team-logos/default.png', '531'),
  ('Guilford', 'guilford', '/team-logos/guilford.png', '2258'),
  ('Gwynedd Mercy', 'gwynedd-mercy', '/team-logos/default.png', '461'),
  ('Hampton', 'hampton', '/team-logos/hampton.png', '2261'),
  ('Han LaGrange', 'han-lagrange', '/team-logos/default.png', '533'),
  ('Hanover', 'hanover', '/team-logos/hanover.png', '2262'),
  ('Harris Stowe', 'harris-stowe', '/team-logos/default.png', '534'),
  ('Hartford', 'hartford', '/team-logos/hartford.png', '42'),
  ('Harvard', 'harvard', '/team-logos/harvard.png', '108'),
  ('Haskell', 'haskell', '/team-logos/default.png', '535'),
  ('Haverford', 'haverford', '/team-logos/default.png', '2265'),
  ('Hawai’i', 'hawai-i', '/team-logos/hawai-i.png', '62'),
  ('Hawai''i Hilo', 'hawaii-hilo', '/team-logos/default.png', '2267'),
  ('Hawaii Pac', 'hawaii-pac', '/team-logos/default.png', '2269'),
  ('Heidelberg', 'heidelberg', '/team-logos/heidelberg.png', '191'),
  ('Hendrix', 'hendrix', '/team-logos/hendrix.png', '418'),
  ('Hendrsn St', 'hendrsn-st', '/team-logos/hendrsn-st.png', '2271'),
  ('High Point', 'high-point', '/team-logos/high-point.png', '2272'),
  ('Hillsdale', 'hillsdale', '/team-logos/hillsdale.png', '2273'),
  ('Hiram', 'hiram', '/team-logos/hiram.png', '2274'),
  ('Hofstra', 'hofstra', '/team-logos/hofstra.png', '2275'),
  ('Holy Cross', 'holy-cross', '/team-logos/holy-cross.png', '107'),
  ('Holy Family', 'holy-family', '/team-logos/holy-family.png', '420'),
  ('Hou Christian', 'hou-christian', '/team-logos/hou-christian.png', '2277'),
  ('Houghton', 'houghton', '/team-logos/default.png', '538'),
  ('Houston', 'houston', '/team-logos/houston.png', '248'),
  ('Howard', 'howard', '/team-logos/howard.png', '47'),
  ('Huston Till', 'huston-till', '/team-logos/default.png', '2281'),
  ('Idaho', 'idaho', '/team-logos/idaho.png', '70'),
  ('Idaho St', 'idaho-st', '/team-logos/idaho-st.png', '304'),
  ('Ill-Springfld', 'ill-springfld', '/team-logos/default.png', '542'),
  ('Illinois', 'illinois', '/team-logos/illinois.png', '356'),
  ('Illinois St', 'illinois-st', '/team-logos/illinois-st.png', '2287'),
  ('Illinois Tech', 'illinois-tech', '/team-logos/default.png', '73'),
  ('Immaculata', 'immaculata', '/team-logos/default.png', '208'),
  ('Indiana', 'indiana', '/team-logos/indiana.png', '84'),
  ('Indiana St', 'indiana-st', '/team-logos/indiana-st.png', '282'),
  ('Iona', 'iona', '/team-logos/iona.png', '314'),
  ('Iowa', 'iowa', '/team-logos/iowa.png', '2294'),
  ('Iowa State', 'iowa-state', '/team-logos/iowa-state.png', '66'),
  ('Ithaca', 'ithaca', '/team-logos/ithaca.png', '175'),
  ('IU Indy', 'iu-indy', '/team-logos/iu-indy.png', '85'),
  ('IU Southeast', 'iu-southeast', '/team-logos/default.png', '387'),
  ('Jacksonville', 'jacksonville', '/team-logos/jacksonville.png', '294'),
  ('James Madison', 'james-madison', '/team-logos/james-madison.png', '256'),
  ('Jax State', 'jax-state', '/team-logos/jax-state.png', '55'),
  ('John Jay', 'john-jay', '/team-logos/default.png', '212'),
  ('Johnson Wales', 'johnson-wales', '/team-logos/default.png', '353'),
  ('Judson', 'judson', '/team-logos/default.png', '546'),
  ('Kalamazoo', 'kalamazoo', '/team-logos/kalamazoo.png', '126'),
  ('Kansas City', 'kansas-city', '/team-logos/kansas-city.png', '140'),
  ('Kennesaw St', 'kennesaw-st', '/team-logos/kennesaw-st.png', '338'),
  ('Kentucky', 'kentucky', '/team-logos/kentucky.png', '96'),
  ('Kenyon', 'kenyon', '/team-logos/kenyon.png', '352'),
  ('King''s', 'kings', '/team-logos/kings.png', '247'),
  ('KS Wesleyn', 'ks-wesleyn', '/team-logos/default.png', '547'),
  ('Lafayette', 'lafayette', '/team-logos/lafayette.png', '322'),
  ('LaGrange', 'lagrange', '/team-logos/lagrange.png', '548'),
  ('Lake Erie', 'lake-erie', '/team-logos/lake-erie.png', '437'),
  ('Lake Superior', 'lake-superior', '/team-logos/lake-superior.png', '285'),
  ('Lawrence', 'lawrence', '/team-logos/lawrence.png', '268'),
  ('Lesley', 'lesley', '/team-logos/default.png', '477'),
  ('Linfield', 'linfield', '/team-logos/linfield.png', '203'),
  ('Lipscomb', 'lipscomb', '/team-logos/lipscomb.png', '288'),
  ('Little Rock', 'little-rock', '/team-logos/little-rock.png', '2031'),
  ('Long Beach St', 'long-beach-st', '/team-logos/long-beach-st.png', '299'),
  ('Loras', 'loras', '/team-logos/loras.png', '263'),
  ('Louisiana', 'louisiana', '/team-logos/louisiana.png', '309'),
  ('Louisville', 'louisville', '/team-logos/louisville.png', '97'),
  ('Loyola (LA)', 'loyola-la', '/team-logos/default.png', '100'),
  ('LSU', 'lsu', '/team-logos/lsu.png', '99'),
  ('Madonna', 'madonna', '/team-logos/default.png', '552'),
  ('Maine', 'maine', '/team-logos/maine.png', '311'),
  ('Maine Mrtm', 'maine-mrtm', '/team-logos/default.png', '274'),
  ('Maine-Farm', 'maine-farm', '/team-logos/default.png', '287'),
  ('Malone', 'malone', '/team-logos/default.png', '556'),
  ('Maran Bap', 'maran-bap', '/team-logos/default.png', '421'),
  ('Marquette', 'marquette', '/team-logos/marquette.png', '269'),
  ('Marshall', 'marshall', '/team-logos/marshall.png', '276'),
  ('Maryland', 'maryland', '/team-logos/maryland.png', '120'),
  ('Marystl', 'marystl', '/team-logos/default.png', '310'),
  ('Mass Mrtme', 'mass-mrtme', '/team-logos/mass-mrtme.png', '110'),
  ('Mayville St', 'mayville-st', '/team-logos/default.png', '561'),
  ('McMurry', 'mcmurry', '/team-logos/mcmurry.png', '241'),
  ('McPherson', 'mcpherson', '/team-logos/default.png', '562'),
  ('ME Fort Kent', 'me-fort-kent', '/team-logos/default.png', '554'),
  ('Memphis', 'memphis', '/team-logos/memphis.png', '235'),
  ('Mesa State', 'mesa-state', '/team-logos/mesa-state.png', '11'),
  ('Methodist', 'methodist', '/team-logos/methodist.png', '291'),
  ('Miami OH', 'miami-oh', '/team-logos/miami-oh.png', '193'),
  ('Michigan', 'michigan', '/team-logos/michigan.png', '130'),
  ('Michigan St', 'michigan-st', '/team-logos/michigan-st.png', '127'),
  ('MidAm Nazarene', 'midam-nazarene', '/team-logos/default.png', '419'),
  ('Milwaukee', 'milwaukee', '/team-logos/milwaukee.png', '270'),
  ('Minn Duluth', 'minn-duluth', '/team-logos/minn-duluth.png', '134'),
  ('Minnesota', 'minnesota', '/team-logos/minnesota.png', '135'),
  ('Mississippi St', 'mississippi-st', '/team-logos/mississippi-st.png', '344'),
  ('Missouri', 'missouri', '/team-logos/missouri.png', '142'),
  ('MIT', 'mit', '/team-logos/mit.png', '109'),
  ('MO Valley', 'mo-valley', '/team-logos/default.png', '136'),
  ('Monstnor', 'monstnor', '/team-logos/monstnor.png', '569'),
  ('Montana', 'montana', '/team-logos/montana.png', '149'),
  ('Montana St', 'montana-st', '/team-logos/montana-st.png', '147'),
  ('Montana Tech', 'montana-tech', '/team-logos/default.png', '148'),
  ('Morehouse', 'morehouse', '/team-logos/morehouse.png', '60'),
  ('Morris', 'morris', '/team-logos/default.png', '571'),
  ('Mount Marty', 'mount-marty', '/team-logos/default.png', '573'),
  ('Mount St Marys', 'mount-st-marys', '/team-logos/mount-st-marys.png', '116'),
  ('Mt Saint Mary', 'mt-saint-mary', '/team-logos/default.png', '289'),
  ('Mtvincent', 'mtvincent', '/team-logos/default.png', '329'),
  ('Murray St', 'murray-st', '/team-logos/murray-st.png', '93'),
  ('N Kentucky', 'n-kentucky', '/team-logos/n-kentucky.png', '94'),
  ('N Michigan', 'n-michigan', '/team-logos/n-michigan.png', '128'),
  ('NC State', 'nc-state', '/team-logos/nc-state.png', '152'),
  ('NC Wesleyan', 'nc-wesleyan', '/team-logos/nc-wesleyan.png', '286'),
  ('Nebraska', 'nebraska', '/team-logos/nebraska.png', '158'),
  ('New Hampshire', 'new-hampshire', '/team-logos/new-hampshire.png', '160'),
  ('New Mexico', 'new-mexico', '/team-logos/new-mexico.png', '167'),
  ('New Mexico St', 'new-mexico-st', '/team-logos/new-mexico-st.png', '166'),
  ('Niagara', 'niagara', '/team-logos/niagara.png', '315'),
  ('North Carolina', 'north-carolina', '/team-logos/north-carolina.png', '153'),
  ('North Dakota', 'north-dakota', '/team-logos/north-dakota.png', '155'),
  ('North Park', 'north-park', '/team-logos/north-park.png', '75'),
  ('North Texas', 'north-texas', '/team-logos/north-texas.png', '249'),
  ('Northeastern', 'northeastern', '/team-logos/northeastern.png', '111'),
  ('Northeastern St', 'northeastern-st', '/team-logos/northeastern-st.png', '196'),
  ('Northrn St', 'northrn-st', '/team-logos/default.png', '425'),
  ('Northwestern', 'northwestern', '/team-logos/northwestern.png', '77'),
  ('Northwood', 'northwood', '/team-logos/default.png', '585'),
  ('Notre Dame', 'notre-dame', '/team-logos/notre-dame.png', '87'),
  ('Oberlin', 'oberlin', '/team-logos/oberlin.png', '391'),
  ('Ohio', 'ohio', '/team-logos/ohio.png', '195'),
  ('Ohio Nrthn', 'ohio-nrthn', '/team-logos/ohio-nrthn.png', '427'),
  ('Ohio State', 'ohio-state', '/team-logos/ohio-state.png', '194'),
  ('OK Christian', 'ok-christian', '/team-logos/default.png', '589'),
  ('Oklahoma', 'oklahoma', '/team-logos/oklahoma.png', '201'),
  ('Oklahoma St', 'oklahoma-st', '/team-logos/oklahoma-st.png', '197'),
  ('Old Dominion', 'old-dominion', '/team-logos/old-dominion.png', '295'),
  ('Ole Miss', 'ole-miss', '/team-logos/ole-miss.png', '145'),
  ('Olivet', 'olivet', '/team-logos/olivet.png', '354'),
  ('Oral Roberts', 'oral-roberts', '/team-logos/oral-roberts.png', '198'),
  ('Oregon St', 'oregon-st', '/team-logos/oregon-st.png', '204'),
  ('Pacific', 'pacific', '/team-logos/pacific.png', '279'),
  ('Pacific Union', 'pacific-union', '/team-logos/default.png', '594'),
  ('Penn', 'penn', '/team-logos/penn.png', '219'),
  ('Penn State', 'penn-state', '/team-logos/penn-state.png', '213'),
  ('Peru State', 'peru-state', '/team-logos/default.png', '596'),
  ('Phildlphia', 'phildlphia', '/team-logos/default.png', '361'),
  ('Pitt', 'pitt', '/team-logos/pitt.png', '221'),
  ('Pitt-Bradford', 'pitt-bradford', '/team-logos/default.png', '220'),
  ('Plattsburgh', 'plattsburgh', '/team-logos/default.png', '177'),
  ('Post', 'post', '/team-logos/post.png', '430'),
  ('Princeton', 'princeton', '/team-logos/princeton.png', '163'),
  ('Pur-Calmet', 'pur-calmet', '/team-logos/pur-calmet.png', '368'),
  ('Redlands', 'redlands', '/team-logos/redlands.png', '29'),
  ('Rhode Island', 'rhode-island', '/team-logos/rhode-island.png', '227'),
  ('Rice', 'rice', '/team-logos/rice.png', '242'),
  ('Richmond', 'richmond', '/team-logos/richmond.png', '257'),
  ('RIT', 'rit', '/team-logos/rit.png', '178'),
  ('Rochester', 'rochester', '/team-logos/rochester.png', '184'),
  ('Rollins', 'rollins', '/team-logos/default.png', '303'),
  ('Rose-Hulm', 'rose-hulm', '/team-logos/rose-hulm.png', '86'),
  ('Rosemont', 'rosemont', '/team-logos/default.png', '465'),
  ('Rutgers', 'rutgers', '/team-logos/rutgers.png', '164'),
  ('Rutgers-Camden', 'rutgers-camden', '/team-logos/default.png', '370'),
  ('S Dak Mnes', 's-dak-mnes', '/team-logos/s-dak-mnes.png', '613'),
  ('S Illinois', 's-illinois', '/team-logos/s-illinois.png', '79'),
  ('Sacramento St', 'sacramento-st', '/team-logos/sacramento-st.png', '16'),
  ('Saint Louis', 'saint-louis', '/team-logos/saint-louis.png', '139'),
  ('San Diego', 'san-diego', '/team-logos/san-diego.png', '301'),
  ('San Diego St', 'san-diego-st', '/team-logos/san-diego-st.png', '21'),
  ('San Fran St', 'san-fran-st', '/team-logos/default.png', '22'),
  ('San José St', 'san-jos-st', '/team-logos/san-jos-st.png', '23'),
  ('Scholastic', 'scholastic', '/team-logos/scholastic.png', '375'),
  ('Sci & Arts OK', 'sci-and-arts-ok', '/team-logos/default.png', '608'),
  ('SE Okla St', 'se-okla-st', '/team-logos/se-okla-st.png', '199'),
  ('Simpson (CA)', 'simpson-ca', '/team-logos/default.png', '612'),
  ('South Alabama', 'south-alabama', '/team-logos/south-alabama.png', '6'),
  ('South Dakota', 'south-dakota', '/team-logos/south-dakota.png', '233'),
  ('South Florida', 'south-florida', '/team-logos/south-florida.png', '58'),
  ('Southern Utah', 'southern-utah', '/team-logos/southern-utah.png', '253'),
  ('St Bonaventure', 'st-bonaventure', '/team-logos/st-bonaventure.png', '179'),
  ('St John Fisher', 'st-john-fisher', '/team-logos/st-john-fisher.png', '374'),
  ('St Mary''s (MD)', 'st-marys-md', '/team-logos/st-marys-md.png', '117'),
  ('St Thom Aq', 'st-thom-aq', '/team-logos/default.png', '123'),
  ('St Thomas (FL)', 'st-thomas-fl', '/team-logos/default.png', '606'),
  ('St. Edward''s', 'st-edwards', '/team-logos/default.png', '244'),
  ('Stanford', 'stanford', '/team-logos/stanford.png', '24'),
  ('State University Col', 'state-university-col', '/team-logos/state-university-col.png', '358'),
  ('Sterling College', 'sterling-college', '/team-logos/default.png', '618'),
  ('Stetson', 'stetson', '/team-logos/stetson.png', '56'),
  ('Stonehill', 'stonehill', '/team-logos/stonehill.png', '284'),
  ('Suffolk', 'suffolk', '/team-logos/default.png', '383'),
  ('SUNY-Oneonta', 'suny-oneonta', '/team-logos/default.png', '355'),
  ('Suny-Potsd', 'suny-potsd', '/team-logos/suny-potsd.png', '182'),
  ('Swarthmore', 'swarthmore', '/team-logos/default.png', '217'),
  ('Syracuse', 'syracuse', '/team-logos/syracuse.png', '183'),
  ('Tabor', 'tabor', '/team-logos/default.png', '619'),
  ('Taylor', 'taylor', '/team-logos/default.png', '620'),
  ('Temple', 'temple', '/team-logos/temple.png', '218'),
  ('Texas', 'texas', '/team-logos/texas.png', '251'),
  ('Texas A&M', 'texas-aandm', '/team-logos/texas-aandm.png', '245'),
  ('Texas A&M-CC', 'texas-aandm-cc', '/team-logos/texas-aandm-cc.png', '357'),
  ('Texas St', 'texas-st', '/team-logos/texas-st.png', '326'),
  ('Towson', 'towson', '/team-logos/towson.png', '119'),
  ('Trinity Tx', 'trinity-tx', '/team-logos/trinity-tx.png', '386'),
  ('Tulsa', 'tulsa', '/team-logos/tulsa.png', '202'),
  ('UAB', 'uab', '/team-logos/uab.png', '5'),
  ('UAlbany', 'ualbany', '/team-logos/ualbany.png', '399'),
  ('UC Col Springs', 'uc-col-springs', '/team-logos/uc-col-springs.png', '2145'),
  ('UC Davis', 'uc-davis', '/team-logos/uc-davis.png', '302'),
  ('UC Irvine', 'uc-irvine', '/team-logos/uc-irvine.png', '300'),
  ('UC Riverside', 'uc-riverside', '/team-logos/uc-riverside.png', '27'),
  ('UC San Diego', 'uc-san-diego', '/team-logos/uc-san-diego.png', '28'),
  ('UCF', 'ucf', '/team-logos/ucf.png', '2116'),
  ('UCLA', 'ucla', '/team-logos/ucla.png', '26'),
  ('UConn', 'uconn', '/team-logos/uconn.png', '41'),
  ('UIC', 'uic', '/team-logos/uic.png', '82'),
  ('UMass', 'umass', '/team-logos/umass.png', '113'),
  ('UMass-Dart', 'umass-dart', '/team-logos/umass-dart.png', '379'),
  ('UNC Wilmington', 'unc-wilmington', '/team-logos/unc-wilmington.png', '350'),
  ('Union TN', 'union-tn', '/team-logos/union-tn.png', '237'),
  ('USC', 'usc', '/team-logos/usc.png', '30'),
  ('UT Arlington', 'ut-arlington', '/team-logos/ut-arlington.png', '250'),
  ('UT Rio Grande', 'ut-rio-grande', '/team-logos/ut-rio-grande.png', '292'),
  ('Utah', 'utah', '/team-logos/utah.png', '254'),
  ('Utah State', 'utah-state', '/team-logos/utah-state.png', '328'),
  ('UTICA', 'utica', '/team-logos/utica.png', '390'),
  ('Valley City', 'valley-city', '/team-logos/default.png', '628'),
  ('Vanderbilt', 'vanderbilt', '/team-logos/vanderbilt.png', '238'),
  ('Vassar', 'vassar', '/team-logos/default.png', '185'),
  ('Vermont', 'vermont', '/team-logos/vermont.png', '261'),
  ('Villanova', 'villanova', '/team-logos/villanova.png', '222'),
  ('Virginia', 'virginia', '/team-logos/virginia.png', '258'),
  ('Virginia St', 'virginia-st', '/team-logos/virginia-st.png', '330'),
  ('Virginia Tech', 'virginia-tech', '/team-logos/virginia-tech.png', '259'),
  ('VT-Lyndon', 'vt-lyndon', '/team-logos/default.png', '551'),
  ('Wake Forest', 'wake-forest', '/team-logos/wake-forest.png', '154'),
  ('Wash St Louis', 'wash-st-louis', '/team-logos/wash-st-louis.png', '143'),
  ('Washington', 'washington', '/team-logos/washington.png', '264'),
  ('Washington St', 'washington-st', '/team-logos/washington-st.png', '265'),
  ('Wayland', 'wayland', '/team-logos/default.png', '630'),
  ('West Virginia', 'west-virginia', '/team-logos/west-virginia.png', '277'),
  ('Western KY', 'western-ky', '/team-logos/western-ky.png', '98'),
  ('Westminster MO', 'westminster-mo', '/team-logos/westminster-mo.png', '433'),
  ('Westminster UT', 'westminster-ut', '/team-logos/default.png', '224'),
  ('Wheaton (IL)', 'wheaton-il', '/team-logos/wheaton-il.png', '396'),
  ('Wingate', 'wingate', '/team-logos/wingate.png', '351'),
  ('Wisconsin', 'wisconsin', '/team-logos/wisconsin.png', '275'),
  ('WISCSUP', 'wiscsup', '/team-logos/default.png', '401'),
  ('Worcester St', 'worcester-st', '/team-logos/worcester-st.png', '402'),
  ('Wsh Advent', 'wsh-advent', '/team-logos/default.png', '408'),
  ('WV Wesleyan', 'wv-wesleyan', '/team-logos/wv-wesleyan.png', '455'),
  ('Yale', 'yale', '/team-logos/yale.png', '43')
ON CONFLICT (name) DO UPDATE
SET slug = EXCLUDED.slug,
    logo_url = EXCLUDED.logo_url,
    espn_team_id = EXCLUDED.espn_team_id;

COMMIT;