import {
  RUSSELL2000_SOURCE,
  RUSSELL2000_TICKER_DATA,
} from "@/lib/market/russell2000Constituents";

const SP500_TICKER_DATA =
  "A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,ADSK,AEE,AEP,AES,AFL,AIG,AIZ,AJG,AKAM,ALB,ALGN,ALL,ALLE,AMAT,AMCR,AMD,AME" +
  ",AMGN,AMP,AMT,AMZN,ANET,AON,AOS,APA,APD,APH,APO,APP,APTV,ARE,ARES,ATO,AVB,AVGO,AVY,AWK,AXON,AXP,AZO,BA,BAC,BALL,BAX,BBY," +
  "BDX,BEN,BF-B,BG,BIIB,BK,BKNG,BKR,BLDR,BLK,BMY,BR,BRK-B,BRO,BSX,BX,BXP,C,CAG,CAH,CARR,CASY,CAT,CB,CBOE,CBRE,CCI,CCL,CDNS," +
  "CDW,CEG,CF,CFG,CHD,CHRW,CHTR,CI,CIEN,CINF,CL,CLX,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COHR,COIN,COO,COP,COR,COST,CPAY,CPB,C" +
  "PRT,CPT,CRH,CRL,CRM,CRWD,CSCO,CSGP,CSX,CTAS,CTRA,CTSH,CTVA,CVNA,CVS,CVX,D,DAL,DASH,DD,DDOG,DE,DECK,DELL,DG,DGX,DHI,DHR,D" +
  "IS,DLR,DLTR,DOC,DOV,DOW,DPZ,DRI,DTE,DUK,DVA,DVN,DXCM,EA,EBAY,ECL,ED,EFX,EG,EIX,EL,ELV,EME,EMR,EOG,EPAM,EQIX,EQR,EQT,ERIE" +
  ",ES,ESS,ETN,ETR,EVRG,EW,EXC,EXE,EXPD,EXPE,EXR,F,FANG,FAST,FCX,FDS,FDX,FE,FFIV,FICO,FIS,FISV,FITB,FIX,FOX,FOXA,FRT,FSLR,F" +
  "TNT,FTV,GD,GDDY,GE,GEHC,GEN,GEV,GILD,GIS,GL,GLW,GM,GNRC,GOOG,GOOGL,GPC,GPN,GRMN,GS,GWW,HAL,HAS,HBAN,HCA,HD,HIG,HII,HLT,H" +
  "ON,HOOD,HPE,HPQ,HRL,HSIC,HST,HSY,HUBB,HUM,HWM,IBKR,IBM,ICE,IDXX,IEX,IFF,INCY,INTC,INTU,INVH,IP,IQV,IR,IRM,ISRG,IT,ITW,IV" +
  "Z,J,JBHT,JBL,JCI,JKHY,JNJ,JPM,KDP,KEY,KEYS,KHC,KIM,KKR,KLAC,KMB,KMI,KO,KR,KVUE,L,LDOS,LEN,LH,LHX,LII,LIN,LITE,LLY,LMT,LN" +
  "T,LOW,LRCX,LULU,LUV,LVS,LYB,LYV,MA,MAA,MAR,MAS,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,META,MGM,MKC,MLM,MMM,MNST,MO,MOS,MPC,MPWR,M" +
  "RK,MRNA,MRSH,MS,MSCI,MSFT,MSI,MTB,MTD,MU,NCLH,NDAQ,NDSN,NEE,NEM,NFLX,NI,NKE,NOC,NOW,NRG,NSC,NTAP,NTRS,NUE,NVDA,NVR,NWS,N" +
  "WSA,NXPI,O,ODFL,OKE,OMC,ON,ORCL,ORLY,OTIS,OXY,PANW,PAYX,PCAR,PCG,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PLD,PLTR,PM,PNC,PNR,P" +
  "NW,PODD,POOL,PPG,PPL,PRU,PSA,PSKY,PSX,PTC,PWR,PYPL,Q,QCOM,RCL,REG,REGN,RF,RJF,RL,RMD,ROK,ROL,ROP,ROST,RSG,RTX,RVTY,SATS," +
  "SBAC,SBUX,SCHW,SHW,SJM,SLB,SMCI,SNA,SNDK,SNPS,SO,SOLV,SPG,SPGI,SRE,STE,STLD,STT,STX,STZ,SW,SWK,SWKS,SYF,SYK,SYY,T,TAP,TD" +
  "G,TDY,TECH,TEL,TER,TFC,TGT,TJX,TKO,TMO,TMUS,TPL,TPR,TRGP,TRMB,TROW,TRV,TSCO,TSLA,TSN,TT,TTD,TTWO,TXN,TXT,TYL,UAL,UBER,UD" +
  "R,UHS,ULTA,UNH,UNP,UPS,URI,USB,V,VICI,VLO,VLTO,VMC,VRSK,VRSN,VRT,VRTX,VST,VTR,VTRS,VZ,WAB,WAT,WBD,WDAY,WDC,WEC,WELL,WFC," +
  "WM,WMB,WMT,WRB,WSM,WST,WTW,WY,WYNN,XEL,XOM,XYL,XYZ,YUM,ZBH,ZBRA,ZTS";

const NASDAQ100_TICKER_DATA =
  "AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,ALNY,AMAT,AMD,AMGN,AMZN,APP,ARM,ASML,AVGO,AXON,BKNG,BKR,CCEP,CDNS,CEG,CHTR,CMCSA,COST,CP" +
  "RT,CRWD,CSCO,CSGP,CSX,CTAS,CTSH,DASH,DDOG,DXCM,EA,EXC,FANG,FAST,FER,FTNT,GEHC,GILD,GOOG,GOOGL,HON,IDXX,INSM,INTC,INTU,IS" +
  "RG,KDP,KHC,KLAC,LIN,LRCX,MAR,MCHP,MDLZ,MELI,META,MNST,MPWR,MRVL,MSFT,MSTR,MU,NFLX,NVDA,NXPI,ODFL,ORLY,PANW,PAYX,PCAR,PDD" +
  ",PEP,PLTR,PYPL,QCOM,REGN,ROP,ROST,SBUX,SHOP,SNDK,SNPS,STX,TMUS,TRI,TSLA,TTWO,TXN,VRSK,VRTX,WBD,WDAY,WDC,WMT,XEL,ZS";

const DOW30_TICKER_DATA =
  "AAPL,AMGN,AMZN,AXP,BA,CAT,CRM,CSCO,CVX,DIS,GS,HD,HON,IBM,JNJ,JPM,KO,MCD,MMM,MRK,MSFT,NKE,NVDA,PG,SHW,TRV,UNH,V,VZ,WMT";

function toTickerSet(csv: string): Set<string> {
  return new Set(
    csv
      .split(",")
      .map((ticker) => ticker.trim().toUpperCase())
      .filter(Boolean)
  );
}

export const SP500_TICKERS = toTickerSet(SP500_TICKER_DATA);
export const NASDAQ100_TICKERS = toTickerSet(NASDAQ100_TICKER_DATA);
export const DOW30_TICKERS = toTickerSet(DOW30_TICKER_DATA);
export const RUSSELL2000_TICKERS = toTickerSet(RUSSELL2000_TICKER_DATA);

export const INDEX_MEMBERSHIP_SOURCES = {
  sp500: "Slickcharts S&P 500 snapshot",
  nasdaq100: "Slickcharts Nasdaq 100 snapshot",
  dow30: "Slickcharts Dow Jones snapshot",
  russell2000: RUSSELL2000_SOURCE,
} as const;

export function getIndexFlags(ticker: string) {
  const normalized = String(ticker ?? "").trim().toUpperCase();

  return {
    isSP500: SP500_TICKERS.has(normalized),
    isNasdaq100: NASDAQ100_TICKERS.has(normalized),
    isDow30: DOW30_TICKERS.has(normalized),
    isRussell2000: RUSSELL2000_TICKERS.has(normalized),
  };
}

export function isMajorIndexMember(row: {
  isSP500?: boolean;
  isNasdaq100?: boolean;
  isDow30?: boolean;
  isRussell2000?: boolean;
}) {
  return Boolean(
    row.isSP500 ||
      row.isNasdaq100 ||
      row.isDow30 ||
      row.isRussell2000
  );
}