export const SECTOR_STOCKS: Record<string, string[]> = {
  Technology: [
    "NVDA", "MSFT", "AAPL", "AVGO", "AMD", "ARM", "ORCL", "CRM", "ADBE", "NOW",
    "IBM", "DELL", "ACN", "QCOM", "CSCO", "INTU", "SHOP", "PANW", "CRWD", "ANET", "SNOW",
  ],
  AI: [
    "NVDA", "AMD", "MSFT", "GOOGL", "META", "AMZN", "PLTR", "SNOW", "CRM", "ORCL",
    "AVGO", "TSM", "ASML", "MU", "ARM", "PANW", "CRWD", "ANET", "DDOG", "NOW",
  ],
  Quantum: [
    "IBM", "INFQ", "IONQ", "QBTS", "QUBT", "RGTI",
  ],
  Semiconductors: [
    "NVDA", "AMD", "AVGO", "ARM", "MU", "TSM", "ASML", "LRCX", "KLAC", "AMAT",
    "QCOM", "TXN", "ADI", "MRVL", "NXPI", "MCHP", "ON", "INTC", "SWKS", "TER",
  ],
  Software: [
    "MSFT", "CRM", "NOW", "ADBE", "ORCL", "SNOW", "DDOG", "PLTR", "MDB", "TEAM",
    "SNPS", "CDNS", "HUBS", "ZS", "NET", "DOCU", "ESTC", "OKTA", "SPLK", "APP",
  ],
  Healthcare: [
    "LLY", "UNH", "JNJ", "ABBV", "MRK", "TMO", "ABT", "ISRG", "AMGN", "PFE",
    "DHR", "SYK", "BSX", "MDT", "REGN", "GILD", "BMY", "CI", "HUM", "CVS",
  ],
  Energy: [
    "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PSX", "VLO", "OXY", "HAL",
    "KMI", "WMB", "OKE", "BKR", "FANG", "DVN", "HES", "CTRA", "APA",
  ],
  "Communication Services": [
    "GOOGL", "META", "NFLX", "TMUS", "VZ", "T", "DIS", "CMCSA", "CHTR", "SPOT",
    "EA", "TTWO", "RBLX", "SNAP", "FOXA", "PARA", "WBD", "ROKU", "LYV", "MTCH",
  ],
  Financials: [
    "JPM", "BAC", "WFC", "GS", "MS", "C", "AXP", "BLK", "SCHW", "USB",
    "PGR", "COF", "BK", "SPGI", "CME", "ICE", "CB", "MMC", "AON", "MSCI",
  ],
  "Consumer Discretionary": [
    "AMZN", "TSLA", "HD", "MCD", "NKE", "SBUX", "LOW", "TGT", "BKNG", "TJX",
    "ROST", "CMG", "MAR", "DIS", "ABNB", "LULU", "ORLY", "AZO", "ULTA", "RCL",
  ],
  "Consumer Staples": [
    "WMT", "COST", "PG", "KO", "PEP", "PM", "MO", "CL", "KMB", "MDLZ",
    "GIS", "KHC", "HSY", "EL", "CLX", "SJM", "KR", "MNST", "KDP", "CHD",
  ],
  Industrials: [
    "GE", "CAT", "DE", "HON", "BA", "LMT", "RTX", "UPS", "UNP", "ETN",
    "GD", "NOC", "PH", "TT", "CMI", "NSC", "RSG", "WM", "ITW", "FAST",
  ],
  Consumer: [
    "AMZN", "TSLA", "HD", "MCD", "NKE", "SBUX", "LOW", "TGT", "COST", "WMT",
    "BKNG", "TJX", "ROST", "CMG", "MAR", "DIS", "ABNB", "LULU", "ORLY", "AZO",
  ],
  Utilities: [
    "NEE", "SO", "DUK", "AEP", "SRE", "XEL", "PEG", "ED", "EXC", "D",
    "PCG", "EIX", "WEC", "ATO", "FE", "CNP", "AWK", "ETR", "EVRG", "AES",
  ],
  Materials: [
    "LIN", "SHW", "APD", "FCX", "ECL", "NEM", "NUE", "DOW", "DD", "MLM",
    "VMC", "ALB", "CTVA", "IFF", "CF", "MOS", "PKG", "BALL", "IP", "EMN",
  ],
  "Real Estate": [
    "AMT", "PLD", "EQIX", "WELL", "O", "SPG", "CCI", "PSA", "CBRE", "EXR",
    "VICI", "EQR", "AVB", "DLR", "SBAC", "INVH", "KIM", "ARE", "BXP", "DOC",
  ],
  "Small Caps": [
    "IWM", "RKLB", "ASTS", "LUNR", "SOUN", "HIMS", "PL", "JOBY", "ACHR", "BBAI",
    "AI", "QBTS", "RGTI", "IONQ", "OKLO", "AVAV", "SMR", "CLSK", "RIOT", "MARA",
  ],
  Dividends: [
    "KO", "PEP", "JNJ", "PG", "VZ", "XOM", "CVX", "ABBV", "MRK", "HD",
    "JPM", "MSFT", "AAPL", "MCD", "PM", "MO", "O", "NEE", "DUK", "WMT",
  ],
  Crypto: [
    "COIN", "MSTR", "MARA", "RIOT", "CLSK", "CORZ", "CIFR", "BTDR", "HUT", "IREN",
    "WULF", "HIVE", "BITF", "ARBK", "CAN", "HOOD", "IBIT", "GBTC", "ETHE", "GLXY",
  ],
  ETFs: [
    "SPY", "QQQ", "IWM", "DIA", "SMH", "SOXX", "ARKK", "XLE", "XLK", "XLF",
    "XLV", "XLI", "XLP", "XLY", "XLC", "XLU", "XLB", "XLRE", "IBIT", "TLT",
  ],
  Options: [
    "HOOD", "IBKR", "SCHW", "CBOE", "CME", "ICE", "SPGI", "MSCI", "COIN", "MSTR",
    "TSLA", "NVDA", "AMD", "PLTR", "META", "AMZN", "QQQ", "SPY", "SMH", "IWM",
  ],
  "Space & Satellite": [
    "RKLB", "ASTS", "LUNR", "PL", "SPCE", "SATS", "GSAT", "VSAT", "IRDM", "JOBY",
    "ACHR", "AVAV", "KTOS", "MRCY", "NOC", "LMT", "RTX", "BA", "HON", "RDW",
  ],
  "Long-term Investing": [
    "MSFT", "AAPL", "NVDA", "AMZN", "GOOGL", "META", "BRK-B", "JPM", "V", "MA",
    "LLY", "UNH", "COST", "WMT", "HD", "PG", "XOM", "AVGO", "VZ", "KO",
  ],
  "Short-term Trading": [
    "TSLA", "NVDA", "AMD", "PLTR", "COIN", "MSTR", "SMCI", "APP", "SOUN", "IONQ",
    "RKLB", "ASTS", "LUNR", "SOFI", "HOOD", "RIOT", "MARA", "RGTI", "BBAI", "AI",
  ],
};

export const COMPANY_NAMES: Record<string, string> = {
  NVDA: "NVIDIA",
  MSFT: "Microsoft",
  AAPL: "Apple",
  AVGO: "Broadcom",
  AMD: "Advanced Micro Devices",
  ARM: "Arm Holdings",
  AMZN: "Amazon",
  ORCL: "Oracle",
  CRM: "Salesforce",
  ADBE: "Adobe",
  NOW: "ServiceNow",
  IBM: "IBM",
  DELL: "Dell Technologies",
  ACN: "Accenture",
  QCOM: "Qualcomm",
  CSCO: "Cisco",
  INTU: "Intuit",
  SHOP: "Shopify",
  PANW: "Palo Alto Networks",
  CRWD: "CrowdStrike",
  ANET: "Arista Networks",
  DDOG: "Datadog",
  MU: "Micron",
  TSM: "Taiwan Semiconductor",
  ASML: "ASML",
  LRCX: "Lam Research",
  KLAC: "KLA",
  AMAT: "Applied Materials",
  TXN: "Texas Instruments",
  ADI: "Analog Devices",
  MRVL: "Marvell Technology",
  NXPI: "NXP Semiconductors",
  MCHP: "Microchip Technology",
  ON: "ON Semiconductor",
  INTC: "Intel",
  SWKS: "Skyworks Solutions",
  TER: "Teradyne",
  SNPS: "Synopsys",
  CDNS: "Cadence Design Systems",
  HUBS: "HubSpot",
  ZS: "Zscaler",
  NET: "Cloudflare",
  DOCU: "DocuSign",
  ESTC: "Elastic",
  OKTA: "Okta",
  SPLK: "Splunk",
  APP: "AppLovin",
  "BRK-B": "Berkshire Hathaway",
  V: "Visa",
  MA: "Mastercard",
  LLY: "Eli Lilly",
  UNH: "UnitedHealth",
  JNJ: "Johnson & Johnson",
  ABBV: "AbbVie",
  MRK: "Merck",
  TMO: "Thermo Fisher",
  ABT: "Abbott",
  ISRG: "Intuitive Surgical",
  AMGN: "Amgen",
  PFE: "Pfizer",
  DHR: "Danaher",
  SYK: "Stryker",
  BSX: "Boston Scientific",
  MDT: "Medtronic",
  REGN: "Regeneron",
  GILD: "Gilead Sciences",
  BMY: "Bristol Myers Squibb",
  CI: "Cigna",
  HUM: "Humana",
  CVS: "CVS Health",
  GOOGL: "Alphabet",
  META: "Meta Platforms",
  NFLX: "Netflix",
  XOM: "Exxon Mobil",
  CVX: "Chevron",
  COP: "ConocoPhillips",
  SLB: "Schlumberger",
  EOG: "EOG Resources",
  MPC: "Marathon Petroleum",
  PSX: "Phillips 66",
  VLO: "Valero",
  OXY: "Occidental Petroleum",
  HAL: "Halliburton",
  KMI: "Kinder Morgan",
  WMB: "Williams Companies",
  OKE: "ONEOK",
  BKR: "Baker Hughes",
  FANG: "Diamondback Energy",
  DVN: "Devon Energy",
  HES: "Hess",
  CTRA: "Coterra Energy",
  APA: "APA Corporation",
  TMUS: "T-Mobile US",
  VZ: "Verizon",
  T: "AT&T",
  CMCSA: "Comcast",
  CHTR: "Charter Communications",
  SPOT: "Spotify",
  EA: "Electronic Arts",
  TTWO: "Take-Two Interactive",
  RBLX: "Roblox",
  SNAP: "Snap",
  FOXA: "Fox",
  PARA: "Paramount Global",
  WBD: "Warner Bros. Discovery",
  ROKU: "Roku",
  LYV: "Live Nation",
  MTCH: "Match Group",
  JPM: "JPMorgan Chase",
  BAC: "Bank of America",
  WFC: "Wells Fargo",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  C: "Citigroup",
  AXP: "American Express",
  BLK: "BlackRock",
  SCHW: "Charles Schwab",
  USB: "U.S. Bancorp",
  PGR: "Progressive",
  COF: "Capital One",
  BK: "Bank of New York Mellon",
  SPGI: "S&P Global",
  CME: "CME Group",
  ICE: "Intercontinental Exchange",
  CB: "Chubb",
  MMC: "Marsh McLennan",
  AON: "Aon",
  MSCI: "MSCI",
  GE: "GE Aerospace",
  CAT: "Caterpillar",
  DE: "Deere",
  HON: "Honeywell",
  BA: "Boeing",
  LMT: "Lockheed Martin",
  RTX: "RTX",
  UPS: "UPS",
  UNP: "Union Pacific",
  ETN: "Eaton",
  GD: "General Dynamics",
  NOC: "Northrop Grumman",
  PH: "Parker-Hannifin",
  TT: "Trane Technologies",
  CMI: "Cummins",
  NSC: "Norfolk Southern",
  RSG: "Republic Services",
  WM: "Waste Management",
  ITW: "Illinois Tool Works",
  FAST: "Fastenal",
  TSLA: "Tesla",
  HD: "Home Depot",
  MCD: "McDonald's",
  NKE: "Nike",
  SBUX: "Starbucks",
  LOW: "Lowe's",
  TGT: "Target",
  COST: "Costco",
  WMT: "Walmart",
  BKNG: "Booking Holdings",
  TJX: "TJX Companies",
  ROST: "Ross Stores",
  CMG: "Chipotle",
  MAR: "Marriott",
  DIS: "Disney",
  ABNB: "Airbnb",
  LULU: "Lululemon",
  ORLY: "O'Reilly Automotive",
  AZO: "AutoZone",
  ULTA: "Ulta Beauty",
  RCL: "Royal Caribbean",
  PG: "Procter & Gamble",
  KO: "Coca-Cola",
  PEP: "PepsiCo",
  PM: "Philip Morris International",
  MO: "Altria",
  CL: "Colgate-Palmolive",
  KMB: "Kimberly-Clark",
  MDLZ: "Mondelez",
  GIS: "General Mills",
  KHC: "Kraft Heinz",
  HSY: "Hershey",
  EL: "Estee Lauder",
  CLX: "Clorox",
  SJM: "J.M. Smucker",
  KR: "Kroger",
  MNST: "Monster Beverage",
  KDP: "Keurig Dr Pepper",
  CHD: "Church & Dwight",
  NEE: "NextEra Energy",
  SO: "Southern Company",
  DUK: "Duke Energy",
  AEP: "American Electric Power",
  SRE: "Sempra",
  XEL: "Xcel Energy",
  PEG: "Public Service Enterprise Group",
  ED: "Con Edison",
  EXC: "Exelon",
  D: "Dominion Energy",
  PCG: "PG&E",
  EIX: "Edison International",
  WEC: "WEC Energy",
  ATO: "Atmos Energy",
  FE: "FirstEnergy",
  CNP: "CenterPoint Energy",
  AWK: "American Water Works",
  ETR: "Entergy",
  EVRG: "Evergy",
  AES: "AES",
  LIN: "Linde",
  SHW: "Sherwin-Williams",
  APD: "Air Products and Chemicals",
  FCX: "Freeport-McMoRan",
  ECL: "Ecolab",
  NEM: "Newmont",
  NUE: "Nucor",
  DOW: "Dow",
  DD: "DuPont",
  MLM: "Martin Marietta Materials",
  VMC: "Vulcan Materials",
  ALB: "Albemarle",
  CTVA: "Corteva",
  IFF: "International Flavors & Fragrances",
  CF: "CF Industries",
  MOS: "Mosaic",
  PKG: "Packaging Corporation of America",
  BALL: "Ball",
  IP: "International Paper",
  EMN: "Eastman Chemical",
  AMT: "American Tower",
  PLD: "Prologis",
  EQIX: "Equinix",
  WELL: "Welltower",
  O: "Realty Income",
  SPG: "Simon Property Group",
  CCI: "Crown Castle",
  PSA: "Public Storage",
  CBRE: "CBRE Group",
  EXR: "Extra Space Storage",
  VICI: "VICI Properties",
  EQR: "Equity Residential",
  AVB: "AvalonBay Communities",
  DLR: "Digital Realty",
  SBAC: "SBA Communications",
  INVH: "Invitation Homes",
  KIM: "Kimco Realty",
  ARE: "Alexandria Real Estate",
  BXP: "BXP",
  DOC: "Healthpeak Properties",
  IWM: "iShares Russell 2000 ETF",
  RKLB: "Rocket Lab",
  ASTS: "AST SpaceMobile",
  LUNR: "Intuitive Machines",
  SOUN: "SoundHound AI",
  HIMS: "Hims & Hers Health",
  PL: "Planet Labs",
  JOBY: "Joby Aviation",
  ACHR: "Archer Aviation",
  BBAI: "BigBear.ai",
  AI: "C3.ai",
  QBTS: "D-Wave Quantum",
  QUBT: "Quantum Computing",
  RGTI: "Rigetti Computing",
  IONQ: "IonQ",
  OKLO: "Oklo",
  SMR: "NuScale Power",
  CLSK: "CleanSpark",
  RIOT: "Riot Platforms",
  MARA: "MARA Holdings",
  COIN: "Coinbase",
  MSTR: "MicroStrategy",
  CORZ: "Core Scientific",
  CIFR: "Cipher Mining",
  BTDR: "Bitdeer",
  HUT: "Hut 8",
  IREN: "IREN",
  WULF: "TeraWulf",
  HIVE: "Hive Digital Technologies",
  BITF: "Bitfarms",
  ARBK: "Argo Blockchain",
  CAN: "Canaan",
  HOOD: "Robinhood",
  IBIT: "iShares Bitcoin Trust",
  GBTC: "Grayscale Bitcoin Trust",
  ETHE: "Grayscale Ethereum Trust",
  GLXY: "Galaxy Digital",
  SPY: "SPDR S&P 500 ETF",
  QQQ: "Invesco QQQ Trust",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  SMH: "VanEck Semiconductor ETF",
  SOXX: "iShares Semiconductor ETF",
  ARKK: "ARK Innovation ETF",
  XLK: "Technology Select Sector SPDR Fund",
  XLF: "Financial Select Sector SPDR Fund",
  XLV: "Health Care Select Sector SPDR Fund",
  XLI: "Industrial Select Sector SPDR Fund",
  XLP: "Consumer Staples Select Sector SPDR Fund",
  XLY: "Consumer Discretionary Select Sector SPDR Fund",
  XLC: "Communication Services Select Sector SPDR Fund",
  XLU: "Utilities Select Sector SPDR Fund",
  XLB: "Materials Select Sector SPDR Fund",
  XLRE: "Real Estate Select Sector SPDR Fund",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  IBKR: "Interactive Brokers",
  CBOE: "Cboe Global Markets",
  SMCI: "Super Micro Computer",
  SPCE: "Virgin Galactic",
  SATS: "EchoStar",
  GSAT: "Globalstar",
  VSAT: "Viasat",
  IRDM: "Iridium Communications",
  MRCY: "Mercury Systems",
  RDW: "Redwire",
  SOFI: "SoFi Technologies",
};

const SECTOR_ALIASES: Record<string, string> = {
  ai: "AI",
  communication: "Communication Services",
  "communication services": "Communication Services",
  consumer: "Consumer Discretionary",
  "consumer discretionary": "Consumer Discretionary",
  "consumer staples": "Consumer Staples",
  crypto: "Crypto",
  dividend: "Dividends",
  dividends: "Dividends",
  etf: "ETFs",
  etfs: "ETFs",
  options: "Options",
  quantum: "Quantum",
  "real estate": "Real Estate",
  "small cap": "Small Caps",
  "small caps": "Small Caps",
  software: "Software",
  space: "Space & Satellite",
  "space & satellite": "Space & Satellite",
  "space and satellite": "Space & Satellite",
  technology: "Technology",
  "long term investing": "Long-term Investing",
  "long-term investing": "Long-term Investing",
  "short term trading": "Short-term Trading",
  "short-term trading": "Short-term Trading",
};

const TICKER_SECTOR_OVERRIDES: Record<string, string> = {
  IBM: "Quantum",
  INFQ: "Quantum",
  IONQ: "Quantum",
  QBTS: "Quantum",
  QUBT: "Quantum",
  RGTI: "Quantum",
};

export function resolveSectorUniverseKey(rawSector: string | null | undefined) {
  const normalizedSector = (rawSector ?? "").trim().toLowerCase();

  if (!normalizedSector || normalizedSector === "all") {
    return "";
  }

  const aliasedSector = SECTOR_ALIASES[normalizedSector];

  if (aliasedSector) {
    return aliasedSector;
  }

  return (
    Object.keys(SECTOR_STOCKS).find(
      (key) => key.toLowerCase() === normalizedSector
    ) ?? ""
  );
}

export function getDisplaySectorForTicker(
  ticker: string | null | undefined,
  fallbackSector: string | null | undefined
) {
  const normalizedTicker = (ticker ?? "").trim().toUpperCase();
  const override = normalizedTicker ? TICKER_SECTOR_OVERRIDES[normalizedTicker] : "";

  if (override) {
    return override;
  }

  const normalizedSector = resolveSectorUniverseKey(fallbackSector);

  if (normalizedSector) {
    return normalizedSector;
  }

  return (fallbackSector ?? "").trim();
}