create table if not exists public.vision_snapshots (
  id bigint generated by default as identity primary key,
  snapshot jsonb not null,
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create index if not exists vision_snapshots_created_at_idx
  on public.vision_snapshots (created_at desc);

alter table public.vision_snapshots enable row level security;