create table if not exists public.sigi_conversation_contexts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  question text not null,
  response_title text not null,
  response_summary text not null,
  cited_tickers text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists sigi_conversation_contexts_user_created_at_idx
  on public.sigi_conversation_contexts (user_id, created_at desc);

alter table public.sigi_conversation_contexts enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sigi_conversation_contexts' and policyname = 'Users can insert their own Sigi conversation contexts'
  ) then
    create policy "Users can insert their own Sigi conversation contexts"
      on public.sigi_conversation_contexts
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sigi_conversation_contexts' and policyname = 'Users can read their own Sigi conversation contexts'
  ) then
    create policy "Users can read their own Sigi conversation contexts"
      on public.sigi_conversation_contexts
      for select
      using (auth.uid() = user_id);
  end if;
end $$;