create table if not exists public.sigi_user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  plan_tier text not null default 'free' check (plan_tier in ('free', 'smart', 'pro')),
  provider text not null default 'openai-compatible',
  base_url text not null default 'https://api.openai.com/v1',
  model text not null default 'gpt-4.1-mini',
  encrypted_api_key text,
  is_enabled boolean not null default false,
  paid_access_enabled boolean not null default false,
  request_limit_per_minute integer not null default 12 check (request_limit_per_minute between 1 and 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sigi_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists sigi_usage_events_user_created_at_idx
  on public.sigi_usage_events (user_id, created_at desc);

alter table public.sigi_user_settings enable row level security;
alter table public.sigi_usage_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sigi_user_settings' and policyname = 'Users can manage their own Sigi settings'
  ) then
    create policy "Users can manage their own Sigi settings"
      on public.sigi_user_settings
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sigi_usage_events' and policyname = 'Users can insert their own Sigi usage events'
  ) then
    create policy "Users can insert their own Sigi usage events"
      on public.sigi_usage_events
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sigi_usage_events' and policyname = 'Users can read their own Sigi usage events'
  ) then
    create policy "Users can read their own Sigi usage events"
      on public.sigi_usage_events
      for select
      using (auth.uid() = user_id);
  end if;
end $$;

create or replace function public.set_sigi_user_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sigi_user_settings_set_updated_at on public.sigi_user_settings;

create trigger sigi_user_settings_set_updated_at
before update on public.sigi_user_settings
for each row execute function public.set_sigi_user_settings_updated_at();