export const fundamentalsPack = [
  {
    id: "roe",
    term: "ROE",
    category: "Fundamentals",
    definition: "Return on Equity measures how efficiently a company generates profit from shareholder equity.",
    explanation: "ROE shows how well management uses investor money. Higher ROE often signals stronger companies.",
    formula: "ROE = Net Income / Shareholder Equity",
    sigiInsight: "Consistently high ROE often appears in elite leadership stocks.",
    example: "Net Income $10M / Equity $50M = 20% ROE",
  },
  {
    id: "pe-ratio",
    term: "P/E Ratio",
    category: "Fundamentals",
    definition: "Price-to-Earnings ratio compares stock price to earnings per share.",
    explanation: "It tells you how expensive a stock is relative to its profits.",
    formula: "P/E = Price / EPS",
    sigiInsight: "High P/E can signal growth expectations-but also risk.",
    example: "Stock $100 / EPS $5 = 20 P/E",
  },
  {
    id: "eps",
    term: "EPS",
    category: "Fundamentals",
    definition: "Earnings Per Share shows profit allocated per share.",
    explanation: "EPS helps measure profitability on a per-share basis.",
    formula: "EPS = Net Income / Shares Outstanding",
    sigiInsight: "Rising EPS trends often support strong price moves.",
    example: "$10M profit / 2M shares = $5 EPS",
  },
  {
    id: "revenue",
    term: "Revenue",
    category: "Fundamentals",
    definition: "Total income generated from business operations.",
    explanation: "Revenue shows how big a company's business is.",
    formula: "Total sales before expenses",
    sigiInsight: "Growth in revenue is often the first signal of expansion.",
    example: "$1B annual sales = $1B revenue",
  },
  {
    id: "revenue-growth",
    term: "Revenue Growth",
    category: "Fundamentals",
    definition: "Rate at which a company's revenue increases over time.",
    explanation: "Shows business expansion speed.",
    formula: "(Current - Previous) / Previous",
    sigiInsight: "High growth companies often drive momentum trades.",
    example: "$100M -> $120M = 20% growth",
  },
  {
    id: "net-income",
    term: "Net Income",
    category: "Fundamentals",
    definition: "Profit after all expenses are deducted.",
    explanation: "This is the company's bottom line.",
    formula: "Revenue - Expenses",
    sigiInsight: "Strong earnings support long-term trends.",
    example: "$1B revenue - $800M costs = $200M net income",
  },
  {
    id: "gross-margin",
    term: "Gross Margin",
    category: "Fundamentals",
    definition: "Percentage of revenue remaining after cost of goods sold.",
    explanation: "Shows efficiency in production.",
    formula: "(Revenue - COGS) / Revenue",
    sigiInsight: "High margin companies tend to dominate sectors.",
    example: "Revenue $100, COGS $60 = 40%",
  },
  {
    id: "operating-margin",
    term: "Operating Margin",
    category: "Fundamentals",
    definition: "Profit percentage after operating expenses.",
    explanation: "Shows core business efficiency.",
    formula: "Operating Income / Revenue",
    sigiInsight: "Improving margins often precede breakouts.",
    example: "$20M / $100M = 20%",
  },
  {
    id: "free-cash-flow",
    term: "Free Cash Flow",
    category: "Fundamentals",
    definition: "Cash remaining after capital expenses.",
    explanation: "Shows real cash strength.",
    formula: "Operating Cash Flow - CapEx",
    sigiInsight: "Strong FCF supports long-term growth.",
    example: "$50M - $20M = $30M",
  },
  {
    id: "debt-to-equity",
    term: "Debt-to-Equity",
    category: "Fundamentals",
    definition: "Ratio of company debt to shareholder equity.",
    explanation: "Measures financial leverage.",
    formula: "Total Debt / Equity",
    sigiInsight: "High debt increases risk during downturns.",
    example: "$100M debt / $50M equity = 2.0",
  },
  {
    id: "market-cap",
    term: "Market Cap",
    category: "Fundamentals",
    definition: "Total value of a company's shares.",
    explanation: "Defines company size.",
    formula: "Price x Shares Outstanding",
    sigiInsight: "Large caps = stability, small caps = volatility.",
    example: "$100 x 1M shares = $100M",
  },
  {
    id: "beta",
    term: "Beta",
    category: "Fundamentals",
    definition: "Beta measures how much a stock moves compared to the overall market, usually the S&P 500.",
    explanation: "Beta shows how volatile a stock is compared to the market. High beta stocks usually move more. Low beta stocks are generally more stable.",
    formula: "Calculated using regression of stock returns vs market returns.",
    sigiInsight: "High beta stocks are great for momentum trades. Low beta stocks are better for stability and defense.",
    example: "Beta 1.0 = moves with market\nBeta 1.5 = moves 50% more than market\nBeta 0.5 = moves half as much",
  },
  {
    id: "52w-high",
    term: "52-Week High",
    category: "Stock Basics",
    definition: "The highest price a stock has traded at over the past 12 months.",
    explanation: "The highest price the stock has reached in the last year. Stocks near their 52-week high often show strength and momentum.",
    formula: "Highest closing or intraday price over the last 252 trading days.",
    sigiInsight: "Stocks pushing toward or breaking above their 52-week high often attract momentum traders.",
    example: "If a stock’s 52-week high is $100 and it trades at $98, it is near breakout territory.",
  },
  {
    id: "52w-low",
    term: "52-Week Low",
    category: "Stock Basics",
    definition: "The lowest price a stock has traded at over the past 12 months.",
    explanation: "The lowest price the stock has reached in the last year. Stocks near their 52-week low may be weak, oversold, or undervalued depending on context.",
    formula: "Lowest closing or intraday price over the last 252 trading days.",
    sigiInsight: "Be careful near 52-week lows. Weak stocks can keep getting weaker unless there is a clear reversal signal.",
    example: "If a stock’s 52-week low is $20 and it trades at $21, it is near its weakest range.",
  },
  {
    id: "book-value",
    term: "Book Value",
    category: "Fundamentals",
    definition: "Net asset value of a company.",
    explanation: "What the company is worth on paper.",
    formula: "Assets - Liabilities",
    sigiInsight: "Useful for value investing comparisons.",
    example: "$500M assets - $200M liabilities = $300M",
  },
  {
    id: "price-to-book",
    term: "Price-to-Book",
    category: "Fundamentals",
    definition: "Stock price compared to book value.",
    explanation: "Shows valuation vs assets.",
    formula: "Price / Book Value",
    sigiInsight: "Low P/B may indicate undervaluation.",
    example: "2.0 = trading at twice book value",
  },
  {
    id: "dividend-yield",
    term: "Dividend Yield",
    category: "Fundamentals",
    definition: "Annual dividend relative to stock price.",
    explanation: "Measures income return.",
    formula: "Dividend / Price",
    sigiInsight: "Higher yields attract income investors.",
    example: "$2 dividend / $100 = 2%",
  },
  {
    id: "return-on-assets",
    term: "ROA",
    category: "Fundamentals",
    definition: "Profit generated from total assets.",
    explanation: "Measures asset efficiency.",
    formula: "Net Income / Total Assets",
    sigiInsight: "Higher ROA = better efficiency.",
    example: "$10M / $100M = 10%",
  },
  {
    id: "operating-income",
    term: "Operating Income",
    category: "Fundamentals",
    definition: "Profit from core operations.",
    explanation: "Excludes non-operating income.",
    formula: "Revenue - Operating Expenses",
    sigiInsight: "Key indicator of business strength.",
    example: "$200M - $150M = $50M",
  },
  {
    id: "current-ratio",
    term: "Current Ratio",
    category: "Fundamentals",
    definition: "Ability to pay short-term liabilities.",
    explanation: "Measures liquidity.",
    formula: "Current Assets / Current Liabilities",
    sigiInsight: "Above 1 = generally healthy.",
    example: "$200M / $100M = 2.0",
  },
  {
    id: "quick-ratio",
    term: "Quick Ratio",
    category: "Fundamentals",
    definition: "Stricter liquidity measure excluding inventory.",
    explanation: "Shows immediate solvency.",
    formula: "(Assets - Inventory) / Liabilities",
    sigiInsight: "Better for stress scenarios.",
    example: "1.5 ratio = strong",
  },
  {
    id: "gross-profit",
    term: "Gross Profit",
    category: "Fundamentals",
    definition: "Revenue minus cost of goods sold.",
    explanation: "Basic profitability measure.",
    formula: "Revenue - COGS",
    sigiInsight: "Growth here supports expansion.",
    example: "$100M - $60M = $40M",
  },
  {
    id: "ebitda",
    term: "EBITDA",
    category: "Fundamentals",
    definition: "Earnings before interest, taxes, depreciation, amortization.",
    explanation: "Shows operational performance.",
    formula: "EBITDA calculation",
    sigiInsight: "Used for comparing companies.",
    example: "Common in valuation models",
  },
  {
    id: "price-to-sales",
    term: "P/S Ratio",
    category: "Fundamentals",
    definition: "Price relative to revenue.",
    explanation: "Used when earnings are negative.",
    formula: "Market Cap / Revenue",
    sigiInsight: "Useful for growth stocks.",
    example: "5x sales",
  },
  {
    id: "earnings-growth",
    term: "Earnings Growth",
    category: "Fundamentals",
    definition: "Increase in profit over time.",
    explanation: "Shows company improvement.",
    formula: "Growth rate",
    sigiInsight: "Drives long-term trends.",
    example: "10% YoY growth",
  },
  {
    id: "free-cash-flow-margin",
    term: "FCF Margin",
    category: "Fundamentals",
    definition: "Free cash flow relative to revenue.",
    explanation: "Measures cash efficiency.",
    formula: "FCF / Revenue",
    sigiInsight: "Higher margin = stronger company.",
    example: "20% margin",
  },
  {
    id: "asset-turnover",
    term: "Asset Turnover",
    category: "Fundamentals",
    definition: "Revenue generated per asset dollar.",
    explanation: "Measures efficiency.",
    formula: "Revenue / Assets",
    sigiInsight: "Higher = more efficient use of assets.",
    example: "1.5x turnover",
  },
] as const;